services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: sklep
      MYSQL_USER: django
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-P", "3306", "-uroot", "-prootpassword" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.local
    restart: on-failure

volumes:
  mysql_data:
